version: "2"

services:

  app:
    build: .
    image: keboola/adwords-extractor
    tty: true
    command: bash
    volumes:
      - ./:/code

  dev-tests:
    image: keboola/adwords-extractor
    command: composer build
    volumes:
      - .:/code
    working_dir: /code
    environment:
      - EX_AW_CLIENT_ID
      - EX_AW_CLIENT_SECRET
      - EX_AW_DEVELOPER_TOKEN
      - EX_AW_REFRESH_TOKEN
      - EX_AW_CUSTOMER_ID
      - EX_AW_TEST_ACCOUNT_ID

  tests:
    image: keboola/adwords-extractor
    command: composer build
    environment:
      - EX_AW_CLIENT_ID
      - EX_AW_CLIENT_SECRET
      - EX_AW_DEVELOPER_TOKEN
      - EX_AW_REFRESH_TOKEN
      - EX_AW_CUSTOMER_ID
      - EX_AW_TEST_ACCOUNT_ID
