version: "2"

services:

  tests:
    build: .
    image: keboola/adwords-extractor
    tty: true
    stdin_open: true
    command: ./tests.sh

  tests-with-report:
    extends:
      service: tests
    volumes:
      - ./.git:/code/.git
    command: sh -c './tests.sh && ./vendor/bin/test-reporter'