version: "2"

services:

  tests:
    build: .
    image: keboola/adwords-extractor
    tty: true
    stdin_open: true
    command: ./tests.sh
    environment:
      - EX_AW_CLIENT_ID
      - EX_AW_CLIENT_SECRET
      - EX_AW_DEVELOPER_TOKEN
      - EX_AW_REFRESH_TOKEN
      - EX_AW_CUSTOMER_ID
      - EX_AW_TEST_ACCOUNT_ID
      - CODECLIMATE_REPO_TOKEN